### ISSUE TITLE
Image Id Issue

### ISSUE THREAD

**Issue by saikiran402** [SIPtopia/CloudFormation#1]
ImageId: ami-0a106fbc465447dd5 Is not available
 can you please help with that

**Comment by SIPtopia** [comment]
Hi @saikiran402 , please make sure you are in r**egion is US-West-2 (Oregon)** and you are searching for **public images**. 

As of today, 1/1/2021, ami-0a106fbc465447dd5 is still available. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/64345845/103437963-ebe7ac00-4c2d-11eb-8888-9891d66853a3.png)
